server:
    port: 8081

spring:
    application:
        name: cms-maintenance-service
    config:
        import: configserver:http://localhost:8888
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
        username: ${database.username}
        password: ${database.password}
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
